name: CI

on:

  push:

    branches: [ "main" ]

jobs:

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Run UnitTests Windows
        run: |
          python -m unittest unit_tests/circle_tests.py
          python -m unittest unit_tests/rectangle_tests.py
          python -m unittest unit_tests/square_tests.py
          python -m unittest unit_tests/triangle_tests.py
